spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/silvestre?&serverTimezone=UTC
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true